# NAME: Seungwon Kim
# EMAIL: haleykim@g.ucla.edu
# ID: 405111152

# Only Error Messages Generated
.SILENT:

# Define Variables
FILES = my_beaglebone.png connected.png copy.png build_run.png git.png Makefile README

# Create Tarball
dist:
	tar -czf lab4a-405111152.tar.gz $(FILES)

# Make Clean
clean:
	rm -R -f lab4a-405111152.tar.gz
